# Generated by Django 5.2.17 on 2026-08-26 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('total_membros', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ocupacao', models.CharField(blank=True, max_length=100)),
                ('escolaridade', models.CharField(blank=True, choices=[('Sem Escolaridade', 'Sem Escolaridade'), ('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Completo', 'Superior Completo')], max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('comorbidade', models.CharField(blank=True, max_length=255)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moradores', to='comunidades.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Canoa', 'Canoa'), ('Barco a Motor', 'Barco a Motor'), ('Barco de Pesca', 'Barco de Pesca'), ('Voadeira', 'Voadeira'), ('Motor-Rabeta', 'Motor-Rabeta'), ('Motocicleta', 'Motocicleta'), ('Bicicleta', 'Bicicleta'), ('Carro', 'Carro'), ('Caminhonete', 'Caminhonete'), ('Outro', 'Outro')], max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('placa', models.CharField(blank=True, max_length=30)),
                ('morador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='comunidades.morador')),
            ],
        ),
    ]
