# Generated by Django 5.2.17 on 2026-08-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0002_investimento_mensalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('certidao', 'Certidão'), ('declaracao', 'Declaração'), ('relatorio', 'Relatório'), ('outro', 'Outro')], max_length=20)),
                ('data_emissao', models.DateField()),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='comunidades.morador')),
            ],
        ),
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.TextField()),
                ('assinado_por', models.CharField(max_length=150)),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='comunidades.documento')),
            ],
        ),
    ]
