# Generated by Django 5.2.17 on 2026-08-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_documento_assinaturadocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('evento', 'Evento'), ('assembleia', 'Assembleia'), ('outro', 'Outro')], default='evento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
