# Generated by Django 5.2.17 on 2026-08-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0004_eventoagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
