# Generated by Django 5.2.17 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=255)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('data_emissao', models.DateField()),
                ('data_protocolo', models.DateField(blank=True, null=True)),
                ('numero_protocolo', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('protocolado', 'Protocolado'), ('respondido', 'Respondido')], default='rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
