# Generated by Django 5.2.17 on 2026-09-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0007_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('infraestrutura', 'Infraestrutura'), ('educacao', 'Educação'), ('saude', 'Saúde'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
