# Generated by Django 5.2.17 on 2026-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0008_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('manutencao', 'Manutenção'), ('energia', 'Energia'), ('agua', 'Água'), ('material', 'Material'), ('evento', 'Evento'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
    ]
