# Generated by Django 5.2.17 on 2026-09-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0009_alter_despesa_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='titulo',
        ),
    ]
