# Generated by Django 5.2.17 on 2026-09-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0010_remove_despesa_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='tipo',
            field=models.CharField(choices=[('reuniao', 'Reunião'), ('evento', 'Evento'), ('assembleia', 'Assembleia'), ('atividade', 'Atividade'), ('outro', 'Outro')], default='evento', max_length=20),
        ),
    ]
