# Generated by Django 5.2.17 on 2026-09-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0011_eventoagenda_responsavel_alter_eventoagenda_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20, null=True),
        ),
    ]
